// src/plugin/vragechat/cef/Chat.vue
<template>
    <div id="chatbox" class="chatBox" :class="{ hide: !isVisible }" tabindex="-1">
      <div id="messageslist" 
         class="messageList" 
         :class="{ scrollbar: settings.scrollbar && !isHidden }" 
         ref="messageList"
         :style="{ height: `${chatSize}em`, overflowY: showScrollbar ? 'auto' : 'hidden' }"
         tabindex="-1">
      <div v-for="(message, index) in messages" 
           :key="index" 
           class="message stroke"
           :class="[message.colorClass, { solidchat: settings.solidchat }]">
        <!-- Use v-html for the message content -->
        <span class="timeStamp" 
              :class="{ 'hide2': !settings.timeStamp }" 
              v-html="message.timestamp"></span>
        <span v-html="message.text"> </span>
      </div>
    </div>
  
      <input v-if="chatInputStatus"
             v-model="inputText"
             @input="updateCharCount"
             @keydown.enter="sendInput"
             @keydown.esc="setChatInputStatus(false)"
             @keydown.up.prevent="onArrowUp"
             @keydown.down.prevent="onArrowDown"
             @keydown.tab.prevent="handleTabComplete"
             :maxlength="settings.maxLength"
             class="inputBar"
             placeholder="Type a message..."
             ref="chatInput" />
  
      <div id="autoComplete" 
           v-html="autoCompleteHtml"
           tabindex="-1">
      </div>
  
      <span id="charCount" 
            :class="{ 'hide': !chatInputStatus, 'charCount stroke': chatInputStatus }"
            tabindex="-1">
        {{ inputText.length }}/{{ settings.maxLength }}
      </span>
    </div>
  </template>
  
  <script>
  export default {
    name: 'ChatApp',
    data() {
      return {
        settings: {
          timeStamp: true,
          removeInputColors: true,
          characterCount: true,
          scrollbar: true,
          maxLength: 255,
          colorBackground: false,
          solidchat: false,
          autohide: 5000
        },
        messages: [],
        inputText: '',
        chatInputStatus: false,
        isVisible: true,
        isHidden: false,
        chatActive: true,
        showScrollbar: true,
        inputHistory: [],
        inputHistoryPosition: -1,
        inputCache: '',
        commands: {},
        command_names: [],
        complete_word: '',
        lang: 'es',
        chatSize: 18,
        autoCompleteHtml: '',
        hideScrollbarTimer: null,
        hideChatTimer: null
      }
    },
    methods: {
      getDateString() {
        const date = new Date()
        const h = '0' + date.getHours().toString()
        const m = '0' + date.getMinutes().toString()
        const s = '0' + date.getSeconds().toString()
        return `[${h.substr(h.length-2)}:${m.substr(m.length-2)}:${s.substr(s.length-2)}] `
      },
      
      levenshteinDistance(str1, str2) {
        const m = str1.length
        const n = str2.length
        const dp = []
  
        for (let i = 0; i <= m; i++) {
          dp[i] = []
          for (let j = 0; j <= n; j++) {
            if (i === 0) {
              dp[i][j] = j
            } else if (j === 0) {
              dp[i][j] = i
            } else {
              dp[i][j] = Math.min(
                dp[i - 1][j - 1] + (str1[i - 1] === str2[j - 1] ? 0 : 1),
                dp[i - 1][j] + 1,
                dp[i][j - 1] + 1
              )
            }
          }
        }
        return dp[m][n]
      },
  
      buscarPalabrasContienen(palabra, lista) {
        const sugerencias = []
        const sugerenciasOrdenadas = []
        for (const comando of lista) {
          if (comando.includes(palabra)) {
            sugerencias.push({ comando, distancia: this.levenshteinDistance(palabra, comando) })
          }
        }
        sugerencias.sort((a, b) => a.distancia - b.distancia)
        for (let i = 0; i < Math.min(5, sugerencias.length); i++) {
          sugerenciasOrdenadas.push(sugerencias[i].comando)
        }
        return sugerenciasOrdenadas
      },
  
      updateCharCount() {
        let message = this.inputText.trim()
        if (message.startsWith('/') && message.length >= 2) {
          const similar_words = this.buscarPalabrasContienen(message.substr(1).toLowerCase(), this.command_names)
          if (similar_words.length > 0) {
            const most_similar = this.commands[similar_words[0]]
            let desc = this.getCommandDescription(most_similar)
            
            let html = `<b>/${similar_words[0]} 
              ${most_similar.args.length > 0 ? `[${most_similar.args.join(' ')}]` : ''} 
              ${most_similar.admin > 0 ? `(ADM: ${most_similar.admin})` : ''} - ${desc}</b>`
  
            const not_so_similar = similar_words.slice(1)
            html += not_so_similar.map((word) => {
              const command = this.commands[word]
              const desc = this.getCommandDescription(command)
              return `<br>/${word} - ${desc}`
            }).join('')
  
            this.autoCompleteHtml = html
            this.complete_word = similar_words[0]
          }
        } else {
          this.autoCompleteHtml = ''
          this.complete_word = ''
        }
      },
  
      getCommandDescription(command) {
        if (typeof command.desc === 'object') {
          return command.desc[this.lang] || command.desc['~~~']
        }
        return typeof command.desc === 'string' ? command.desc : '~~~'
      },
  
      handleTabComplete() {
        if (this.complete_word.length > 0) {
          this.inputText = `/${this.complete_word}`
          this.complete_word = ''
        }
      },
  
      setChatInputStatus(status) {
        if ((!this.chatActive && status) || (status === this.chatInputStatus)) return
  
        if (typeof mp !== 'undefined') {
          mp.invoke("focus", status)
          mp.invoke("setTypingInChatState", status)
          mp.trigger("player::chatOpen", JSON.stringify({status: status}))
        }
  
        this.chatInputStatus = status
        if (status) {
          if (this.settings.scrollbar) {
            this.showScrollbar = true
            if (this.hideScrollbarTimer) {
              clearTimeout(this.hideScrollbarTimer)
            }
            this.hideScrollbarTimer = setTimeout(() => {
              this.showScrollbar = false
            }, 10000)
          }
          this.$nextTick(() => {
            this.$refs.chatInput?.focus()
          })
        } else {
          this.autoCompleteHtml = ''
        }
      },
  
      sendInput() {
        let message = this.inputText.trim()
  
        if (this.settings.removeInputColors) {
          message = message.replace(/(?=!{).*(?<=})/g, '')
        }
  
        if (message.length < 1) {
          this.setChatInputStatus(false)
          return
        }
  
        if (message[0] === '/') {
          if (message.length < 2) {
            this.setChatInputStatus(false)
            return
          }
          if (typeof mp !== 'undefined') {
            mp.invoke('command', message.substr(1))
          } else {
            this.pushMessage(message)
          }
        } else {
          if (typeof mp !== 'undefined') {
            mp.invoke('chatMessage', message)
          } else {
            this.pushMessage(`6${message}`)
          }
        }
  
        this.inputHistory.unshift(message)
        if (this.inputHistory.length > 100) {
          this.inputHistory.pop()
        }
        
        this.inputText = ''
        this.inputHistoryPosition = -1
        this.setChatInputStatus(false)
      },
  
      onArrowUp() {
        if (this.inputHistoryPosition === this.inputHistory.length - 1) return
        
        if (this.inputHistoryPosition === -1) {
          this.inputCache = this.inputText
        }
  
        this.inputHistoryPosition++
        this.inputText = this.inputHistory[this.inputHistoryPosition]
      },
  
      onArrowDown() {
        if (this.inputHistoryPosition === -1) return
  
        if (this.inputHistoryPosition === 0) {
          this.inputText = this.inputCache
          this.inputHistoryPosition = -1
          return
        }
  
        this.inputHistoryPosition--
        this.inputText = this.inputHistory[this.inputHistoryPosition]
      },
  
      pushMessage(text) {
        let colorClass = ''
        let processedText = text

        // Process color classes same as before
        switch(text[0]) {
          case '0':
            processedText = text.substr(1)
            colorClass = 'color-purple'
            break
          case '1':
            processedText = text.substr(1)
            if (this.settings.colorBackground) {
              processedText = `🚩 ${processedText}`
            }
            colorClass = 'color-error'
            break
          // ... other cases remain the same ...
        }

        if (!this.settings.colorBackground) {
          colorClass += ' hide3'
        }

        // The message text is now treated as HTML
        this.messages.push({
          text: processedText,
          timestamp: this.getDateString(),
          colorClass
        })

        // Trim messages if there are too many
        if (this.messages.length > 100) {
          this.messages.shift()
        }

        // Scroll to bottom and handle timers
        this.$nextTick(() => {
          const messageList = this.$refs.messageList
          if (messageList) {
            messageList.scrollTop = messageList.scrollHeight
          }
        })
  
        if (this.settings.scrollbar) {
          this.showScrollbar = true
          if (this.hideScrollbarTimer) {
            clearTimeout(this.hideScrollbarTimer)
          }
          this.hideScrollbarTimer = setTimeout(() => {
            this.showScrollbar = false
          }, 8000)
  
          if (this.settings.autohide > 0) {
            if (this.hideChatTimer) {
              clearTimeout(this.hideChatTimer)
            }
            if (!this.isHidden) {
              this.hideChatTimer = setTimeout(() => {
                this.isHidden = true
              }, this.settings.autohide)
            }
          }
        }
      },

      clearMessages() {
        this.messages = []
      },

      activateChat(toggle) {
        if (!toggle && this.chatActive) {
          this.setChatInputStatus(false)
        }
        this.chatActive = toggle
      },

      showChat(toggle) {
        if (!toggle && this.chatInputStatus) {
          this.setChatInputStatus(false)
        }
        this.isHidden = !toggle
        this.isVisible = toggle
        this.chatActive = toggle
      },

      setFontSize(size) {
        if (this.$el) {
          this.$el.style.fontSize = `${size}px`
        }
      },

      setChatSize(size) {
        this.chatSize = size
      },

      setCommands(commandsStr, lang) {
        this.commands = JSON.parse(commandsStr)
        this.command_names = Object.keys(this.commands)
        this.lang = lang
      },

      toggleSolidChat() {
        this.settings.solidchat = !this.settings.solidchat
      }
    },
    mounted() {
        window.Chat = {
          setCommandsTest: this.setCommands('{"test": {"desc": "Test command", "args": [], "admin": 0}}', 'es'),
          enableTimestamp: (status) => {this.settings.timeStamp = status},
          enableColorBackground: (status) => {this.settings.colorBackground = status},
          fontSize: (size) => {this.setFontSize(size)},
          chatSize: (size) => {this.setChatSize(size)},
          enableSolidChat: (status) => {this.settings.solidchat = !this.settings.solidchat},
          enableScrollbar: (status) => {this.settings.scrollbar = !this.settings.scrollbar},
          enableCharacterCount: (status) => {this.settings.characterCount = status},
          enableAutohide: (time) => {this.settings.autohide = time},
          clearChat: () => {this.clearMessages()},
          showChat: (status) => {this.showChat(status)},
          activateChat: (status) => {this.activateChat(status)},
        }

        window.addEventListener('keydown', (e) => {
          if (e.key === 't' && !this.chatInputStatus && this.chatActive) {
            this.setChatInputStatus(true)
            e.preventDefault()
          }
        })
  
        this.pushMessage('Chat iniciado')

        window.chatSetCommands = (commandsStr, lang) => {
          console.log('Setting commands', commandsStr, lang)
          this.setCommands(commandsStr, lang)
        }

        if (typeof mp !== 'undefined') {
        const api = {
          'chat:push': this.pushMessage,
          'chat:clear': this.clearMessages,
          'chat:activate': this.activateChat,
          'chat:show': this.showChat,
          'chat:solidchat': this.toggleSolidChat,
          'chat:fontSize': this.setFontSize,
          'chat:chatSize': this.setChatSize,
        }
        


        for (const [eventName, handler] of Object.entries(api)) {
          mp.events.add(eventName, handler)
        }
      }
    },
    beforeUnmount() {
      if (typeof mp !== 'undefined') {
        const events = [
          'chat:push',
          'chat:clear',
          'chat:activate',
          'chat:show',
          'chat:solidchat',
          'chat:fontSize',
          'chat:chatSize',
        ]

        for (const event of events) {
          mp.events.remove(event)
        }
      }
      window.chatSetCommands = null

      if (this.hideScrollbarTimer) {
        clearTimeout(this.hideScrollbarTimer)
      }
      if (this.hideChatTimer) {
        clearTimeout(this.hideChatTimer)
      }
    }
  }


  </script>

  <style src="./main.css"></style>

// src/plugin/vragechat/cef/Chat.tsx
import React, { useState, useEffect, useRef, useCallback } from 'react';
import { ChatSettings, ChatMessage, ChatCommands } from './types';
import { ChatBridge } from './chatbridge';
import './main.css'

const ChatApp: React.FC = () => {
  // State
  const [settings, setSettings] = useState<ChatSettings>({
    timeStamp: true,
    removeInputColors: true,
    characterCount: true,
    scrollbar: true,
    maxLength: 255,
    colorBackground: false,
    solidchat: false,
    autohide: 5000
  });

  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [inputText, setInputText] = useState('');
  const [chatInputStatus, setChatInputStatus] = useState(false);
  const [isVisible, setIsVisible] = useState(true);
  const [isHidden, setIsHidden] = useState(false);
  const [chatActive, setChatActive] = useState(true);
  const [showScrollbar, setShowScrollbar] = useState(true);
  const [inputHistory, setInputHistory] = useState<string[]>([]);
  const [inputHistoryPosition, setInputHistoryPosition] = useState(-1);
  const [inputCache, setInputCache] = useState('');
  const [commands, setCommands] = useState<ChatCommands>({});
  const [commandNames, setCommandNames] = useState<string[]>([]);
  const [completeWord, setCompleteWord] = useState('');
  const [lang, setLang] = useState('es');
  const [chatSize, setChatSize] = useState(18);
  const [autoCompleteHtml, setAutoCompleteHtml] = useState('');

  // Refs
  const messageListRef = useRef<HTMLDivElement>(null);
  const chatInputRef = useRef<HTMLInputElement>(null);
  const hideScrollbarTimerRef = useRef<number | null>(null);
  const hideChatTimerRef = useRef<number | null>(null);
  const chatBridgeRef = useRef<ChatBridge>(ChatBridge.getInstance());

  // Utility functions
  const getDateString = useCallback(() => {
    const date = new Date();
    const h = '0' + date.getHours().toString();
    const m = '0' + date.getMinutes().toString();
    const s = '0' + date.getSeconds().toString();
    return `[${h.substr(h.length-2)}:${m.substr(m.length-2)}:${s.substr(s.length-2)}] `;
  }, []);

  const levenshteinDistance = useCallback((str1: string, str2: string): number => {
    const m = str1.length;
    const n = str2.length;
    const dp: number[][] = Array(m + 1).fill(null).map(() => Array(n + 1).fill(0));

    for (let i = 0; i <= m; i++) {
      for (let j = 0; j <= n; j++) {
        if (i === 0) dp[i][j] = j;
        else if (j === 0) dp[i][j] = i;
        else {
          dp[i][j] = Math.min(
            dp[i - 1][j - 1] + (str1[i - 1] === str2[j - 1] ? 0 : 1),
            dp[i - 1][j] + 1,
            dp[i][j - 1] + 1
          );
        }
      }
    }
    return dp[m][n];
  }, []);

  const findSimilarWords = useCallback((word: string, list: string[]): string[] => {
    const suggestions = list
      .filter(comando => comando.includes(word))
      .map(comando => ({
        comando,
        distancia: levenshteinDistance(word, comando)
      }))
      .sort((a, b) => a.distancia - b.distancia)
      .slice(0, 5)
      .map(s => s.comando);
    
    return suggestions;
  }, [levenshteinDistance]);

  const getCommandDescription = useCallback((command: any): string => {
    if (!command) return '~~~';
    if (typeof command.desc === 'object') {
      return command.desc[lang] || command.desc['~~~'];
    }
    return typeof command.desc === 'string' ? command.desc : '~~~';
  }, [lang]);

  // Core chat functions
  const handleChatInputStatus = useCallback((status: boolean) => {
    if ((!chatActive && status) || (status === chatInputStatus)) return;

    if (typeof mp !== 'undefined') {
      mp.invoke("focus", status);
      mp.invoke("setTypingInChatState", status);
      mp.trigger("player::chatOpen", JSON.stringify({status}));
    }

    setChatInputStatus(status);
    
    if (status) {
      if (settings.scrollbar) {
        setShowScrollbar(true);
        if (hideScrollbarTimerRef.current) {
          clearTimeout(hideScrollbarTimerRef.current);
        }
        hideScrollbarTimerRef.current = setTimeout(() => {
          setShowScrollbar(false);
        }, 10000);
      }
      // Remove the direct focus call from here as it might be too early
    } else {
      setAutoCompleteHtml('');
    }
  }, [chatActive, chatInputStatus, settings.scrollbar]);

  const updateCharCount = useCallback((message: string) => {
    message = message.trim();
    if (message.startsWith('/') && message.length >= 2) {
      const similarWords = findSimilarWords(message.substr(1).toLowerCase(), commandNames);
      if (similarWords.length > 0) {
        const mostSimilar = commands[similarWords[0]];
        const desc = getCommandDescription(mostSimilar);
        
        let html = `<b>/${similarWords[0]} 
          ${mostSimilar.args?.length > 0 ? `[${mostSimilar.args.join(' ')}]` : ''} 
          ${mostSimilar.admin > 0 ? `(ADM: ${mostSimilar.admin})` : ''} - ${desc}</b>`;

        const notSoSimilar = similarWords.slice(1);
        html += notSoSimilar.map((word) => {
          const command = commands[word];
          const desc = getCommandDescription(command);
          return `<br>/${word} - ${desc}`;
        }).join('');

        setAutoCompleteHtml(html);
        setCompleteWord(similarWords[0]);
      }
    } else {
      setAutoCompleteHtml('');
      setCompleteWord('');
    }
  }, [commands, commandNames, findSimilarWords, getCommandDescription]);


  const scrollToBottom = useCallback(() => {
    if (messageListRef.current) {
      // Use requestAnimationFrame to ensure the scroll happens after the render
      requestAnimationFrame(() => {
        if (messageListRef.current) {
          messageListRef.current.scrollTop = messageListRef.current.scrollHeight;
        }
      });
    }
  }, []);

  const pushMessage = useCallback((text: string) => {
    let colorClass = '';
    let processedText = text;

    switch(text[0]) {
      case '0':
        processedText = text.substr(1);
        colorClass = 'color-purple';
        break;
      case '1':
        processedText = text.substr(1);
        if (settings.colorBackground) {
          processedText = `🚩 ${processedText}`;
        }
        colorClass = 'color-error';
        break;
    }

    if (!settings.colorBackground) {
      colorClass += ' hide3';
    }

    setMessages(prev => {
      const newMessages = [...prev, {
        text: processedText,
        timestamp: getDateString(),
        colorClass
      }];
      if (newMessages.length > 100) {
        return newMessages.slice(-100);
      }
      return newMessages;
    });

    // Schedule scroll after state update
    setTimeout(scrollToBottom, 0);

    if (settings.scrollbar) {
      setShowScrollbar(true);
      if (hideScrollbarTimerRef.current) {
        clearTimeout(hideScrollbarTimerRef.current);
      }
      hideScrollbarTimerRef.current = setTimeout(() => {
        setShowScrollbar(false);
      }, 8000);
    }

    if (settings.autohide > 0) {
      if (hideChatTimerRef.current) {
        clearTimeout(hideChatTimerRef.current);
      }

      if (!isHidden) {
        setIsHidden(false);
        hideChatTimerRef.current = setTimeout(() => {
          setIsHidden(true);
        }, settings.autohide);
      } else {
        setIsHidden(false);
      }
    } else if (isHidden)
      setIsHidden(false);

  }, [settings, getDateString, isHidden, scrollToBottom]);

  useEffect(() => {
    scrollToBottom();
  }, [messages, scrollToBottom]);

  const sendInput = useCallback(() => {
    let message = inputText.trim();

    if (settings.removeInputColors) {
      message = message.replace(/(?=!{).*(?<=})/g, '');
    }

    if (message.length < 1) {
      handleChatInputStatus(false);
      return;
    }

    if (message[0] === '/') {
      if (message.length < 2) {
        handleChatInputStatus(false);
        return;
      }
      if (typeof mp !== 'undefined') {
        mp.invoke('command', message.substr(1));
      } else {
        pushMessage(message);
      }
    } else {
      if (typeof mp !== 'undefined') {
        mp.invoke('chatMessage', message);
      } else {
        pushMessage(`6${message}`);
      }
    }

    setInputHistory(prev => [message, ...prev.slice(0, 99)]);
    setInputText('');
    setInputHistoryPosition(-1);
    handleChatInputStatus(false);
  }, [inputText, settings.removeInputColors, handleChatInputStatus, pushMessage]);

  const onArrowUp = useCallback((e: React.KeyboardEvent) => {
    e.preventDefault();
    if (inputHistoryPosition === inputHistory.length - 1) return;
    
    if (inputHistoryPosition === -1) {
      setInputCache(inputText);
    }

    const newPosition = inputHistoryPosition + 1;
    setInputHistoryPosition(newPosition);
    setInputText(inputHistory[newPosition]);
  }, [inputHistoryPosition, inputHistory, inputText]);

  const onArrowDown = useCallback((e: React.KeyboardEvent) => {
    e.preventDefault();
    if (inputHistoryPosition === -1) return;

    if (inputHistoryPosition === 0) {
      setInputText(inputCache);
      setInputHistoryPosition(-1);
      return;
    }

    const newPosition = inputHistoryPosition - 1;
    setInputHistoryPosition(newPosition);
    setInputText(inputHistory[newPosition]);
  }, [inputHistoryPosition, inputCache, inputHistory]);

  const handleTabComplete = useCallback((e: React.KeyboardEvent) => {
    e.preventDefault();
    if (completeWord.length > 0) {
      setInputText(`/${completeWord}`);
      setCompleteWord('');
    }
  }, [completeWord]);

  // Chat management functions
  const chatManagement = {
    clearMessages: useCallback(() => {
      setMessages([]);
    }, []),

    activateChat: useCallback((toggle: boolean) => {
      if (!toggle && chatActive) {
        handleChatInputStatus(false);
      }
      setChatActive(toggle);
    }, [chatActive, handleChatInputStatus]),

    showChat: useCallback((toggle: boolean) => {
      if (!toggle && chatInputStatus) {
        handleChatInputStatus(false);
      }
      setIsHidden(!toggle);
      setIsVisible(toggle);
      setChatActive(toggle);
    }, [chatInputStatus, handleChatInputStatus]),

    setFontSize: useCallback((size: number) => {
      const element = document.getElementById('chatbox');
      if (element) {
        element.style.fontSize = `${size}px`;
      }
    }, []),

    enableAutohide: useCallback((time: number) => {
      setSettings(prev => ({ ...prev, autohide: time }));
    }, []),

    enableColorBackground: useCallback((status: boolean) => {
      setSettings(prev => ({ ...prev, colorBackground: status }));
    }, []),

    setCommandsAndLang: useCallback((commandsStr: string, lang: string) => {
      const parsedCommands = JSON.parse(commandsStr);
      setCommands(parsedCommands);
      setCommandNames(Object.keys(parsedCommands));
      setLang(lang);
    }, []),

    toggleSolidChat: useCallback(() => {
      setSettings(prev => ({ ...prev, solidchat: !prev.solidchat }));
    }, [])
  };

  // Handle keydown events
  const handleKeyDown = useCallback((e: KeyboardEvent) => {
    // Only handle 't' key if we're not already typing in an input
    if (e.key.toLowerCase() === 't' && 
        !chatInputStatus && 
        chatActive && 
        !(e.target instanceof HTMLInputElement || e.target instanceof HTMLTextAreaElement)) {
      handleChatInputStatus(true);
      e.preventDefault();
    }
  }, [chatInputStatus, chatActive, handleChatInputStatus]);

  // Setup and cleanup effects
  useEffect(() => {
    const bridge = chatBridgeRef.current;

    // Setup global chat methods
    bridge.setupGlobalChat({
      setCommands: chatManagement.setCommandsAndLang,
      clearMessages: chatManagement.clearMessages,
      activateChat: chatManagement.activateChat,
      showChat: chatManagement.showChat,
      setFontSize: chatManagement.setFontSize,
      setChatSize,
      toggleSolidChat: chatManagement.toggleSolidChat,
      setSettings,
      enableAutohide: chatManagement.enableAutohide,
      enableColorBackground: chatManagement.enableColorBackground
    });

    // Setup MP events
    bridge.setupMPEvents({
      'chat:push': pushMessage,
      'chat:clear': chatManagement.clearMessages,
      'chat:activate': chatManagement.activateChat,
      'chat:show': chatManagement.showChat,
      'chat:solidchat': chatManagement.toggleSolidChat,
      'chat:fontSize': chatManagement.setFontSize,
      'chat:chatSize': setChatSize,
    });

    // Add keydown listener
    window.addEventListener('keydown', handleKeyDown);
    
    // Initial message
    pushMessage('Chat iniciado');

    return () => {
      bridge.cleanup();
      window.removeEventListener('keydown', handleKeyDown);
      
      if (hideScrollbarTimerRef.current) {
        clearTimeout(hideScrollbarTimerRef.current);
      }
      if (hideChatTimerRef.current) {
        clearTimeout(hideChatTimerRef.current);
      }
    };
  }, []);

  useEffect(() => {
    if (chatInputStatus) {
      // Use a small delay to ensure the input has rendered
      const focusTimer = setTimeout(() => {
        chatInputRef.current?.focus();
      }, 0);
      
      return () => clearTimeout(focusTimer);
    } 

    return 
  }, [chatInputStatus]);

  return (
    <div 
      id="chatbox"
      className={`chatBox ${!isVisible ? 'hide' : ''}`}
      tabIndex={-1}
    >
      <div
        id="messageslist"
        className={`messageList ${settings.scrollbar && showScrollbar ? 'scrollbar' : ''}`}
        ref={messageListRef}
        style={{
          display:(isHidden && settings.autohide > 0) ? 'none' : 'block',
          height: `${chatSize}em`,
          overflowY: showScrollbar ? 'auto' : 'hidden'
        }}
        tabIndex={-1}
      >
        {messages.map((message, index) => (
          <div
            key={index}
            className={`message stroke ${message.colorClass} ${settings.solidchat ? 'solidchat' : ''}`}
          >
            <span 
              className={`timeStamp ${!settings.timeStamp ? 'hide2' : ''}`}
              dangerouslySetInnerHTML={{ __html: message.timestamp }}
            />
            <span dangerouslySetInnerHTML={{ __html: message.text }} />
          </div>
        ))}
      </div>

      {chatInputStatus && (
        <input
          value={inputText}
          onChange={(e) => {
            setInputText(e.target.value);
            updateCharCount(e.target.value);
          }}
          onKeyDown={(e) => {
            switch (e.key) {
              case 'Enter':
                sendInput();
                break;
              case 'Escape':
                handleChatInputStatus(false);
                break;
              case 'ArrowUp':
                onArrowUp(e);
                break;
              case 'ArrowDown':
                onArrowDown(e);
                break;
              case 'Tab':
                handleTabComplete(e);
                break;
            }
          }}
          maxLength={settings.maxLength}
          className="inputBar"
          placeholder="Type a message..."
          ref={chatInputRef}
        />
      )}

      <div
        id="autoComplete"
        dangerouslySetInnerHTML={{ __html: autoCompleteHtml }}
        tabIndex={-1}
      />

      <span
        id="charCount"
        className={`${!chatInputStatus ? 'hide' : ''} ${chatInputStatus ? 'charCount stroke' : ''}`}
        tabIndex={-1}
      >
        {inputText.length}/{settings.maxLength}
      </span>
    </div>
  );
};

export default ChatApp;
